---
syncthing_folder_path: /media/backup
syncthing_max_kbps: 122070
syncthing_ignore_patterns:
  - "*.dat"
  - "*.tmp"
syncthing_devices:
  - name: topi
    id: "WN46LT4-JHS5IHX-BEQD22I-NYZ54DM-NXITJH7-OAPV7W3-GVJCJGC-SOQUOQX"
    address: "2001:913:1000:10::14"
  - name: nam
    id: "FEUIFKO-6Q2JOJY-5UUPXRS-JOBBW5P-5WSM5XX-3DZNOKJ-M5JNOE4-LKUVSQR"
    address: "2001:913:1000:10::15"
  - name: bour
    id: "Q4XCL62-LTESPFU-RWNKHX6-EJTHYSL-4PUHRZV-LQ3J34S-S4A6XLX-HC5HLAM"
    address: "2001:913:1000:10::16"
