---
- name: Installation de Caddy2
  ansible.builtin.import_role:
    name: caddy_server
  tags: ['caddy']

- name: Installation de PHP FPM
  ansible.builtin.import_role:
    name: php_fpm
  vars:
    php_version: "{{ grav_php_version }}"
    php_extra_modules:
      - yaml
      - sqlite3
      - intl
    # Grav handles php session name by itself
    php_fpm_session_name: ""
  tags: ['php_fpm']

- name: Installation de Composer
  ansible.builtin.import_role:
    name: composer
  tags: ['composer']

- name: Création de l'utilisateur {{ grav_owner }}
  ansible.builtin.user:
    name: "{{ grav_owner }}"
    home: "/var/www/{{ grav_owner }}"
    shell: /sbin/nologin
    system: true
    state: present

- name: Création du dossier /var/www
  ansible.builtin.file:
    path: /var/www
    owner: caddy
    group: caddy
    mode: "u=rwx,go=rx"
    state: directory

- name: Création du dossier racine du site
  ansible.builtin.file:
    path: "/var/www/{{ grav_owner }}/dist"
    owner: "{{ grav_owner }}"
    group: "{{ grav_owner }}"
    mode: "u=rwx,go=rx"
    state: directory

- name: Copie de la configuration php-fpm
  ansible.builtin.template:
    src: php-fpm/php-pool.conf.j2
    dest: "/etc/php/{{ grav_php_version }}/fpm/pool.d/{{ grav_owner }}.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - Reload php-fpm
  tags: ['php_config']

- name: Création du dossier tmp pour php-fpm
  ansible.builtin.file:
    path: "/var/www/{{ grav_owner }}/tmp"
    owner: "{{ grav_owner }}"
    group: "{{ grav_owner }}"
    mode: "u=rwx,g=rx,o="
    state: directory

- name: Trigger php-fpm handlers
  ansible.builtin.meta: flush_handlers

- name: Copie de la configuration Caddy2
  ansible.builtin.template:
    src: "caddy/grav.j2"
    dest: "/etc/caddy/conf.d/{{ grav_owner }}.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
    validate: caddy validate --adapter caddyfile --config %s
  notify: Reload caddy
  tags: ['caddy_config']

- name: Trigger Caddy handlers
  ansible.builtin.meta: flush_handlers

- name: Installation du scheduler
  ansible.builtin.import_tasks: scheduler.yml
  tags: ['scheduler']

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/grav.yml.j2
    dest: /etc/borgmatic.d/grav-{{ grav_owner }}.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ['borgmatic_config']
