---
- name: Installation de Docker
  ansible.builtin.import_tasks: docker.yml
  tags: ['docker']

- name: Installation de Gitlab Runner
  ansible.builtin.import_tasks: gitlab_runner.yml
  tags: ['gitlab_runner']
