---
- name: Installation de docker
  ansible.builtin.import_role:
    name: docker
  tags: ['docker']

- name: Installation de Gitlab Runner
  ansible.builtin.import_tasks: gitlab_runner.yml
  tags: ['gitlab_runner']
