workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.venv/"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  FF_USE_FASTZIP: "true"

stages:
  - quality

linting:
  image: python:3.13
  stage: quality
  script:
    - chmod o= -R . # This is needed because somehow the repository is world-writable
    - echo "fake_password" > vault.key # Faking vault password file because it doesn't exists in the CI
    - |
      if [[ ! -d .venv ]]; then
        python3 -m venv .venv
      fi
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - pre-commit run --all-files --color always
  cache:
    key:
      files:
        - .pre-commit-config.yaml
        - requirements.txt
    paths:
      - ${PRE_COMMIT_HOME}
      - ${PIP_CACHE_DIR}
    policy: pull-push
  interruptible: true
