---
- name: Importation des variables spécifiques à l'OS
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution_release }}.yml"

- name: Installation de Ceph
  ansible.builtin.import_role:
    name: ceph
  tags: ["ceph"]

- name: Suppression de l'ancien dépôt APT pour Proxmox
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-install-repo.list
    state: absent

- name: Ajout du dépôt APT pour Proxmox
  ansible.builtin.deb822_repository:
    name: pve-install-repo
    types: deb
    signed_by: "{{ proxmox_gpg_key_url }}"
    uris: http://download.proxmox.com/debian/pve
    suites: "{{ ansible_distribution_release }}"
    components:
      - pve-no-subscription
    state: present
  notify: Update apt cache

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Configuration de l'exporteur InfluxDB de Proxmox
  ansible.builtin.copy:
    src: pve/status.cfg
    dest: /etc/pve/status.cfg
    owner: root
    group: www-data
    mode: u=rw,g=r

- name: Suppression de la permission à l'utilisateur telegraf d'exécuter certaines commandes sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^telegraf'
    line: 'telegraf ALL=(ALL) NOPASSWD: /usr/sbin/smartctl, /usr/bin/ipmitool'
    validate: 'visudo -cf %s'
  tags: ['sudo']

- name: Installation de ipmi_exporter
  ansible.builtin.import_role:
    name: ipmi_exporter
  tags: ["ipmi_exporter"]

- name: Installation de smartctl exporter
  ansible.builtin.import_role:
    name: smartctl_exporter
  tags: ["smartctl_exporter"]

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/proxmox.yml.j2
    dest: /etc/borgmatic.d/proxmox.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ["borgmatic_config"]
