- name: Suppression de l'ancien dépôt APT pour Zammad
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/zammad.list
    state: absent

- name: Ajout du dépôt APT pour Zammad
  ansible.builtin.deb822_repository:
    name: zammad
    types: deb
    signed_by: https://go.packager.io/srv/deb/zammad/zammad/gpg-key.gpg
    uris: https://go.packager.io/srv/deb/zammad/zammad/stable/debian
    suites: "{{ ansible_distribution_major_version }}"
    components:
      - main
    state: present
  notify: Update apt cache

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Installation de Zammad
  ansible.builtin.package:
    name: zammad
    state: present

- name: Configuration de la connexion à la base de données
  ansible.builtin.template:
    src: zammad/database.yml.j2
    dest: /opt/zammad/config/database.yml
    owner: zammad
    group: zammad
    mode: "u=rw,go="
  notify:
    - Migrate zammad db
    - Seed zammad db
    - Restart zammad

- name: Trigger Zammad handlers
  ansible.builtin.meta: flush_handlers

- name: Désactivation de Nginx
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: false

- name: Désactivation de PostgreSQL en local
  ansible.builtin.service:
    name: postgresql
    state: stopped
    enabled: false
  when: postgresql_host != "localhost"

- name: Test si Zammad est connecté à ElasticSearch
  ansible.builtin.command:
    cmd: zammad run rails r "puts Setting.get('es_url')"
  changed_when: false
  register: _zammad_elasticsearch_configured

- name: Connexion de Zammad à ElasticSearch
  ansible.builtin.command:
    cmd: zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
  changed_when: true
  when: _zammad_elasticsearch_configured.stdout == ""

- name: Reconstruction des indices ElasticSearch
  ansible.builtin.command:
    cmd: zammad run rails zammad:searchindex:rebuild
  changed_when: true
  when: _zammad_elasticsearch_configured.stdout == ""

- name: Activation de Zammad au démarrage
  ansible.builtin.service:
    name: zammad
    state: started
    enabled: true
