- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kafka
  ansible.builtin.systemd:
    name: kafka
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
