dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: trixie-collectd-exporter-molecule
    box: debian/trixie64
    cpu: 2
    memory: 512
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
      vault_password_file: "${MOLECULE_PROJECT_DIRECTORY}/../../vault.key"
    ssh_connection:
      pipelining: true
verifier:
  name: ansible
