---
- name: Création du fichier auth.log
  file:
    path: /var/log/auth.log
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: root
    group: adm
    mode: "u+rw,g+r,o-r"

- name: Installation de fail2ban
  apt:
    name: fail2ban
    state: present
  tags: fail2ban

- name: Copie de la configuration fail2ban
  copy:
    src: "{{ inventory_hostname }}/fail2ban/jail.local"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "u+rw,go+r"
  notify: restart fail2ban
  register: fail2ban_conf
  failed_when:
  - fail2ban_conf.msg is defined
  # Don't fail when the source file cannot be found
  - "'Could not find or access' not in fail2ban_conf.msg"
  tags: fail2ban

- name: Activation de fail2ban au démarrage
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: fail2ban