---
- name: Installation de python3-debian
  ansible.builtin.package:
    name: python3-debian

- name: Repos debian (deb822)
  ansible.builtin.deb822_repository:
    name: debian
    types: deb
    uris: "{{ commun_repos_mirror }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    components:
      - main
      - contrib
      - non-free
  when: ansible_distribution_major_version | int >= 12
  notify: Update apt cache

- name: Repos debian-updates (deb822)
  ansible.builtin.deb822_repository:
    name: debian-updates
    types: deb
    uris: "{{ commun_repos_mirror }}"
    suites: "{{ ansible_facts['distribution_release'] }}-updates"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    components:
      - main
      - contrib
      - non-free
  when: ansible_distribution_major_version | int >= 12
  notify: Update apt cache

- name: Repos debian-backports (deb822)
  ansible.builtin.deb822_repository:
    name: debian-backports
    types: deb
    uris: "{{ commun_repos_mirror }}"
    suites: "{{ ansible_facts['distribution_release'] }}-backports"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    components:
      - main
      - contrib
      - non-free
  when: ansible_distribution_major_version | int >= 12
  notify: Update apt cache

- name: Repos debian-security (deb822)
  ansible.builtin.deb822_repository:
    name: debian-security
    types: deb
    uris: "{{ commun_repos_mirror_security }}"
    suites: "{{ ansible_facts['distribution_release'] }}-security"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    components:
      - main
      - contrib
      - non-free
  when: ansible_distribution_major_version | int >= 12
  notify: Update apt cache

- name: Empty old sources.list (deb822)
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "ugo=r"
  when: ansible_distribution_major_version | int >= 12
  notify: Update apt cache

- name: Repos debian (sources.list)
  ansible.builtin.copy:
    src: "apt/{{ ansible_facts['distribution_release'] }}_sources.list"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "ugo=r"
  when: ansible_distribution_major_version | int < 12
  notify: Update apt cache

- name: Trigger APT handler
  ansible.builtin.meta: flush_handlers

- name: Installation de unattended-upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Copie du template unattended-upgrade
  ansible.builtin.template:
    src: repos/50unattended-upgrades.j2
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: root
    group: root
    mode: "ugo=r"

- name: Copie du template 20auto-updates
  ansible.builtin.copy:
    src: repos/20auto-updates
    dest: "/etc/apt/apt.conf.d/20auto-updates"
    owner: root
    group: root
    mode: "ugo=r"

- name: Creation du répertoire pour les clés GPG
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"
