---
- name: Installation de divers outils
  ansible.builtin.package:
    name:
      - git
      - unzip
      - htop
      - tree
      - wget
      - curl
      - nano
      - molly-guard
      - vim
      - mosh
      - qemu-guest-agent
      - ncdu
      - screen
      - rsync
      - tmux
      - sudo
      - ca-certificates
      - openssl
      - jq
      - dbus
      - safe-rm
      - bash-completion
      - psmisc # provide killall
      - kitty-terminfo # terminal Tharyrok
      - zstd
      - python3-systemd
      # See https://www.reddit.com/r/OpenMediaVault/comments/1rlrll1/who_command_not_showing_logged_in_users_after/
      - libpam-systemd
    state: present
