---
- name: Restart syncthing@root
  ansible.builtin.systemd:
    name: syncthing@root
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
