- name: Installation de GPG
  ansible.builtin.package:
    name:
      - gpg
      - gpg-agent
      - dirmngr
    state: present

- name: Suppression de l'ancien dépôt APT pour Eclipse Temurin
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/temurin.list
    state: absent
  tags: ["temurin_install"]

- name: Suppression de l'ancienne clé GPG pour Eclipse Temurin
  ansible.builtin.file:
    path: /etc/apt/keyrings/temurin.asc
    state: absent
  tags: ["temurin_install"]

- name: Ajout du dépôt APT pour Eclipse Temurin
  ansible.builtin.deb822_repository:
    name: temurin
    types: deb
    uris: https://packages.adoptium.net/artifactory/deb
    suites: "{{ ansible_distribution_release }}"
    components: [main]
    signed_by: https://packages.adoptium.net/artifactory/api/gpg/key/public
  notify: Update apt cache
  tags: ["temurin_install"]

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Installation de Eclipse Temurin
  ansible.builtin.package:
    name: "temurin-{{ jdk_temurin_major_version }}-jdk"
    state: present
  tags: ["temurin_install"]
