- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded

- name: Restart vector
  ansible.builtin.service:
    name: vector
    state: restarted
