---
- name: Prepare
  hosts: all
  become: true

  pre_tasks:
    - name: Mise à jour du cache APT
      ansible.builtin.apt:
        update_cache: true

    - name: Installation de python3-debian
      ansible.builtin.package:
        name: python3-debian
        state: present

  roles:
    - vector
    - borgmatic
