- hosts: all
  # connect to the containers through lxd
  connection: lxd
  gather_facts: no
  vars:
    lxd_bridge_name: neutrinetbr0
  tasks:
  - name: "Définition de l'adresse IPv4 locale"
    set_fact:
      ip_address: "{{ hostvars[inventory_hostname].ansible_host }}"

  - name: "Définition du nom du conteneur"
    set_fact:
      ansible_host: "{{ inventory_hostname_short }}"

  - name: Création du profil LXC pour Neutrinet
    raw: |
      lxc profile create neutrinet 2>/dev/null
      lxc profile edit neutrinet <<< "{{ lookup('template', 'lxd/profile.yml.j2') }}"
    tags: [lxc, lxc_profile]
    delegate_to: localhost
    changed_when: no
    run_once: yes

  - name: Création du bridge LXC pour Neutrinet
    raw: |
      lxc network create {{ lxd_bridge_name }}
      lxc network edit {{ lxd_bridge_name }} <<< "{{ lookup('file', 'lxd/network.yml') }}"
    tags: [lxc, lxc_network]
    delegate_to: localhost
    changed_when: no
    run_once: yes
    
  - name: Création des conteneurs LXC
    lxd_container:
      # container name is based on the hostname
      name: "{{ inventory_hostname_short }}"
      state: "{{ container_state | default('started') }}"
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        alias: debian/{{ debian_release | default('buster') }}/amd64
        protocol: simplestreams
      profiles:
      - neutrinet
      config:
        security.nesting: 'true'
        security.privileged: 'false'

      # uncomment if you installed lxd using snap
      # url: unix:/var/snap/lxd/common/lxd/unix.socket
      wait_for_ipv4_addresses: true
      timeout: 600
    delegate_to: localhost
    tags: [lxc, lxc_container]

  - name: Vérification de la présence de python
    block:
    - name: Vérification de l'installation de python3
      raw: python3 --version
      changed_when: no
    rescue:
    - name: Installation de python3
      raw: apt install -y python3
    tags: python
  
  - name: Configuration de l'adresse IPv4 statique
    template:
      src: network/interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: "u+rw,og+r"
    notify: restart network
    tags: network

  - name: Récupération des informations de l'OS
    gather_facts:
    tags: always
  
  - name: Configuration commune de chaque host
    import_role:
      name: commun

  handlers:
  - name: restart network
    service:
      name: networking
      state: restarted