---
haproxy:
  - hostname: ketupa.vagrant.neutrinet.me
    target:
      - ketupa.vagrant.neutri.net
    target_port: 80
    healthcheck: false

haproxy_redirect: []

haproxy_postgresql: []

haproxy_listen:
  - "[::]"

letsencrypt_mail_notification: "{{ mail_notification }}"

letsencrypt_post_hook: ''
letsencrypt_deploy_hook: ''

letsencrypt_dns_gandi_api_key: ''
letsencrypt_dns_gandi_sharing_id: ''
letsencrypt_staging: true
letsencrypt_domains_gandi: []
