---
syncthing_listen_address: "::"
syncthing_folder_path: changeme
syncthing_max_kbps: 0
# syncthing_ignore_patterns:
#   - "*.swp"
syncthing_ignore_patterns: []
# syncthing_devices:
#   - name: nam
#     id: "AAAAAAA-BBBBBBB-CCCCCCC-DDDDDDD-EEEEEEE-FFFFFFF-GGGGGGG-HHHHHHH"
#     address: "2001:913:1000:10::15"
#   - name: bour
#     id: "IIIIIII-JJJJJJJ-KKKKKKK-LLLLLLL-MMMMMMM-NNNNNNN-OOOOOOO-PPPPPPP"
#     address: "2001:913:1000:10::16"
syncthing_devices: []
