---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart clickhouse-server
  ansible.builtin.systemd:
    name: clickhouse-server
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
