---

- name: Installer le knot
  ansible.builtin.import_tasks:
    file: install.yml

- name: Config knot
  ansible.builtin.import_tasks:
    file: config.yml

- name: Activer le service knot
  ansible.builtin.import_tasks:
    file: service.yml

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/knot.yml.j2
    dest: /etc/borgmatic.d/knot.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ['borgmatic_config']

- name: Vérification que l'exporteur Prometheus est prêt
  ansible.builtin.uri:
    url: http://localhost:9433/metrics
    method: GET
  register: _knot_module_prometheus
  retries: 10
  delay: 5
  until: _knot_module_prometheus is success

- name: Configuration de vector
  ansible.builtin.template:
    src: vector/prometheus_knot_exporter.yaml.j2
    dest: /etc/vector/sources/prometheus_knot_exporter.yaml
    owner: vector
    group: vector
    mode: "ug=r,o="
  notify: Restart vector
  tags: ['vector_config']
