---

- name: service | Enable and start service
  ansible.builtin.service:
    name: knot
    state: started
    enabled: true

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: service | Copie du service knot-exporter
  ansible.builtin.copy:
    src: systemd/knot-exporter.service
    dest: /etc/systemd/system/knot-exporter.service
    owner: root
    group: root
    mode: "ugo=r"

- name: service | Enable and start service
  ansible.builtin.service:
    name: knot-exporter
    state: started
    enabled: true
