---
- name: Converge
  hosts: all
  become: true

  vars:
    syncthing_folder_path: /srv/syncthing-test

  pre_tasks:
    - name: Mise à jour du cache APT
      ansible.builtin.apt:
        update_cache: true

  roles:
    - syncthing
