---
- name: Converge
  hosts: all
  become: true

  vars:
    bird_peers_upstreams:
      - asn: 204059
        neighbor_ipv6: fdc9:94e5:e86::190
        neighbor_ipv6_interface: lo
        name: "Route Reflector 01"
        slug: route_reflector_01
        type: route-reflector
    bird_peers_downstreams: []

  roles:
    - hsflowd
