- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart uptime-kuma
  ansible.builtin.service:
    name: uptime-kuma
    state: restarted

- name: Restart vector
  ansible.builtin.service:
    name: vector
    state: restarted
