---
- name: Suppression de l'ancien dépôt APT pour Yarn
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/yarn.list
    state: absent

- name: Ajout du dépôt APT pour Yarn
  ansible.builtin.deb822_repository:
    name: yarn
    types: deb
    signed_by: https://dl.yarnpkg.com/debian/pubkey.gpg
    uris: https://dl.yarnpkg.com/debian
    suites: stable
    components:
      - main
    state: present
  notify: Update apt cache

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Installation de Yarn
  ansible.builtin.package:
    name: yarn
    state: present
