---

- name: Installation de Collectd exporter
  ansible.builtin.import_tasks: collectd_exporter.yml
  tags: ['collectd_exporter']

- name: Nettoyage des archives de Collectd exporter
  ansible.builtin.import_tasks: cleanup.yml
  tags: ['cleanup']

- name: Configuration de la source vector
  ansible.builtin.template:
    src: vector/collectd_exporter.yaml.j2
    dest: /etc/vector/sources/collectd_exporter.yaml
    owner: vector
    group: vector
    mode: "ug=r,o="
  notify: Restart vector
  tags: ['vector_config']

- name: Configuration de la transformation vector
  ansible.builtin.template:
    src: vector/transforms/prometheus_collectd_exporter.yaml.j2
    dest: /etc/vector/transforms/prometheus_collectd_exporter.yaml
    owner: vector
    group: vector
    mode: "ug=r,o="
  notify: Restart vector
  tags: ['vector_config']
