---

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted

- name: restart sshguard
  service: 
    name: sshguard
    state: restarted

- name: restart nftables
  service:
    name: nftables
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
