- name: Installation de Routinator
  ansible.builtin.import_tasks: routinator.yml
  tags: ['routinator']

- name: Configuration de vector
  ansible.builtin.template:
    src: vector/prometheus_routinator_exporter.yaml.j2
    dest: /etc/vector/sources/prometheus_routinator_exporter.yaml
    owner: vector
    group: vector
    mode: "ug=r,o="
  notify: Restart vector
  tags: ['vector_config']

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/routinator.yml.j2
    dest: /etc/borgmatic.d/routinator.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ['borgmatic_config']
