---
- name: Déploiement de Syncthing
  hosts: syncthing
  become: true

  pre_tasks:
    - name: Mise à jour du cache APT
      ansible.builtin.apt:
        update_cache: true

  roles:
    - syncthing
