---

- name: Installation de podman
  ansible.builtin.package:
    name: podman
    state: present
  tags: ['podman']

- name: Activer le socket Podman
  ansible.builtin.service:
    name: podman.socket
    state: started
    enabled: true

- name: Créer le répertoire des quadlets
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: Installation de authentik
  ansible.builtin.import_tasks:
    file: authentik.yml
  tags: ['authentik']

## Presentement un bug sur le parsing de la sortie prometheus de authentik
# - name: Configuration telegraf
#   ansible.builtin.import_tasks:
#     file: telegraf.yml

- name: Configuration des backup
  ansible.builtin.import_tasks:
    file: backup.yml
  tags: ['backup']
