- name: Détection du serveur PostgreSQL primaire
  ansible.builtin.import_tasks: patroni.yml
  when: postgresql_patroni_hosts | length > 0

- name: Suppression de l'ancien dépôt APT pour PostgreSQL
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/postgresql.list
    state: absent
  tags: ["postgresql_install"]

- name: Ajout du dépôt APT pour PostreSQL
  ansible.builtin.deb822_repository:
    name: postgresql
    types: deb
    signed_by: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    uris: http://apt.postgresql.org/pub/repos/apt
    suites: "{{ ansible_distribution_release }}-pgdg"
    components:
      - main
    state: present
  notify: Update apt cache
  tags: ["postgresql_install"]

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Installation des dépendences
  ansible.builtin.package:
    name:
      - postgresql-client-{{ postgresql_major_version }}
      - acl
    state: present

- name: Création de la base de données PostgreSQL {{ postgresql_db_name }}
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
    state: present
  become: true
  become_user: postgres
  delegate_to: "{{ postgresql_patroni_primary_host | default(inventory_hostname) }}"

- name: Création de l'utilisateur PostgreSQL {{ postgresql_db_name }}
  community.postgresql.postgresql_user:
    login_db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_db_name }}"
    password: "{{ postgresql_db_password }}"
    role_attr_flags: "{{ postgresql_db_role_attributes }}"
  become: true
  become_user: postgres
  delegate_to: "{{ postgresql_patroni_primary_host | default(inventory_hostname) }}"
  no_log: true

- name: Octroi des privilèges à l'utilisateur PostgreSQL {{ postgresql_db_name }}
  community.postgresql.postgresql_privs:
    login_db: "{{ postgresql_db_name }}"
    priv: ALL
    type: database
    role: "{{ postgresql_db_name }}"
    state: present
  become: true
  become_user: postgres
  delegate_to: "{{ postgresql_patroni_primary_host | default(inventory_hostname) }}"

# See https://stackoverflow.com/questions/22483555/postgresql-give-all-permissions-to-a-user-on-a-postgresql-database
- name: Octroi du privilège CREATE sur le schéma public à l'utilisateur PostgreSQL {{ postgresql_db_name }}
  community.postgresql.postgresql_privs:
    login_db: "{{ postgresql_db_name }}"
    priv: CREATE
    type: schema
    objs: public
    role: "{{ postgresql_db_name }}"
    state: present
  become: true
  become_user: postgres
  delegate_to: "{{ postgresql_patroni_primary_host | default(inventory_hostname) }}"

- name: Changement du propriétaire de la base de données
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
    owner: "{{ postgresql_db_name }}"
    state: present
  become: true
  become_user: postgres
  delegate_to: "{{ postgresql_patroni_primary_host | default(inventory_hostname) }}"
  when: postgresql_db_change_owner
