---
- name: Installation des certificats Let's Encrypt
  ansible.builtin.import_tasks: letsencrypt.yml
  tags: ['letsencrypt']

- name: Installation de x509 certificate exporter
  ansible.builtin.import_role:
    name: x509_certificate_exporter
  tags: ['x509_certificate_exporter']

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/letsencrypt.yml.j2
    dest: /etc/borgmatic.d/letsencrypt.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ['borgmatic_config']
