---
- name: Provisionning des machines Debian
  ansible.builtin.import_playbook: apps/debian_commun.yml

- name: Configuration de Proxmox
  ansible.builtin.import_playbook: apps/proxmox.yml

- name: Configuration de PBS
  ansible.builtin.import_playbook: apps/pbs.yml

- name: Déploiement de Keepalived
  ansible.builtin.import_playbook: apps/keepalived.yml

- name: Déploiement de HAProxy
  ansible.builtin.import_playbook: apps/haproxy.yml

- name: Déploiement du cluster Patroni pour PostgreSQL
  ansible.builtin.import_playbook: apps/postgres_patroni.yml

- name: Déploiement des sites web statiques
  ansible.builtin.import_playbook: apps/web_static.yml

- name: Déploiement des webhooks
  ansible.builtin.import_playbook: apps/webhook.yml

- name: Déploiement du cluster Ceph S3
  ansible.builtin.import_playbook: apps/ceph_s3.yml

- name: Déploiement de Semaphore
  ansible.builtin.import_playbook: apps/semaphore.yml

- name: Déploiement de HedgeDoc
  ansible.builtin.import_playbook: apps/hedgedoc.yml

- name: Déploiement de Mattermost
  ansible.builtin.import_playbook: apps/mattermost.yml

- name: Déploiement de Nextcloud
  ansible.builtin.import_playbook: apps/nextcloud.yml

- name: Déploiement de Accounting
  ansible.builtin.import_playbook: apps/accounting.yml

- name: Déploiement de Backoffice
  ansible.builtin.import_playbook: apps/backoffice.yml

- name: Déploiement de Grav
  ansible.builtin.import_playbook: apps/grav.yml

- name: Déploiement de Dokuwiki
  ansible.builtin.import_playbook: apps/dokuwiki.yml

- name: Déploiement de Zammad
  ansible.builtin.import_playbook: apps/zammad.yml

- name: Déploiement de Mobilizon
  ansible.builtin.import_playbook: apps/mobilizon.yml

- name: Déploiement des probes pour le monitoring
  ansible.builtin.import_playbook: apps/probe.yml

- name: Déploiement de Bird Exporter
  ansible.builtin.import_playbook: apps/bird_exporter.yml

- name: Déploiement de Collectd Exporter
  ansible.builtin.import_playbook: apps/collectd_exporter.yml

- name: Déploiement de VictoriaMetrics
  ansible.builtin.import_playbook: apps/victoriametrics.yml

- name: Déploiement d'Alertmanager
  ansible.builtin.import_playbook: apps/alertmanager.yml

- name: Déploiement de Grafana
  ansible.builtin.import_playbook: apps/grafana.yml

- name: Déploiement de Uptime-Kuma
  ansible.builtin.import_playbook: apps/uptime_kuma.yml

- name: Déploiement de Gitlab Runner
  ansible.builtin.import_playbook: apps/gitlab_runner.yml

- name: Déploiement de Stalwart
  ansible.builtin.import_playbook: apps/stalwart.yml

- name: Déploiement de Knot
  ansible.builtin.import_playbook: apps/knot.yml
