---
- name: Installation de Caddy2
  ansible.builtin.import_role:
    name: caddy_server
  tags: ['caddy_install']

- name: Installation des sites statiques
  ansible.builtin.include_tasks:
    file: static_website.yml
  loop: "{{ web_static_domains }}"
  loop_control:
    loop_var: domain
    label: "{{ domain.name }}"
  vars:
    domain_owner: "{{ domain.name | replace('.', '-') }}"
