---
- name: Suppression de la clé GPG de InfluxDB
  ansible.builtin.file:
    path: /etc/apt/keyrings/{{ item }}
    state: absent
  loop:
    - influxdb.asc
    - telegraf.asc

- name: Suppression du dépôt APT pour Telegraf
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - telegraf.list
    - telegraf.sources

- name: Suppression de Telegraf
  ansible.builtin.package:
    name: telegraf
    state: absent

- name: Suppression du dossier de configuration Telegraf
  ansible.builtin.file:
    path: /etc/telegraf
    state: absent

- name: Suppression de l'utilisateur telegraf
  ansible.builtin.user:
    name: telegraf
    state: absent
