---
- name: Suppression de la clé GPG de InfluxDB
  ansible.builtin.file:
    path: /etc/apt/keyrings/influxdb.asc
    state: absent

- name: Suppression du dépôt APT pour Telegraf
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/telegraf.list
    state: absent

- name: Suppression de Telegraf
  ansible.builtin.package:
    name: telegraf
    state: absent

- name: Suppression du dossier de configuration Telegraf
  ansible.builtin.file:
    path: /etc/telegraf
    state: absent

- name: Suppression de l'utilisateur telegraf
  ansible.builtin.user:
    name: telegraf
    state: absent
