---
- name: Installation de x509 certificate exporter
  ansible.builtin.import_tasks: x509_certificate_exporter.yml
  tags: ['x509_certificate_exporter']

- name: Nettoyage des archives de x509 certificate exporter
  ansible.builtin.import_tasks: cleanup.yml
  tags: ['cleanup']

- name: Configuration de vector
  ansible.builtin.template:
    src: vector/prometheus_x509_certificate_exporter.yaml.j2
    dest: /etc/vector/sources/prometheus_x509_certificate_exporter.yaml
    owner: vector
    group: vector
    mode: "ug=r,o="
  notify: Restart vector
  tags: ['vector_config']
